export const AD_LP_SLUGS = [
  "dia-das-maes",
  "dia-dos-namorados",
  "urgencia",
  "aniversario",
  "rosas-apt",
  "lirios-apt",
  "carro-low",
  "carro-high",
  "presente-hoje",
  "tradicao-comprovacao",
  "sem-erro",
  "qual-b",
  "so-porque-sim",
  "buque-real",
  "reconciliacao",
  "girassol",
  "catalogo-precos",
] as const;
